apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapspot-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snapspot-api
  template:
    metadata:
        labels:
          app: snapspot-api
    spec:
      containers:
        - name: snapspot-api
          image: snapspot-api
          imagePullPolicy: Never