apiVersion: v1
kind: Pod
metadata:
  name: snapspot-api
spec:
  containers:
    - name: snapspot-api
      image: snapspot-api
      imagePullPolicy: Never
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2 # Default 1
        periodSeconds: 5 # Defaults 10
        failureThreshold: 1 # Defaults 3