apiVersion: v1
kind: Service
metadata:
  name: snapspot-api
spec:
  type: NodePort
  selector:
    app: snapspot-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePost: 32555